### ISSUE TITLE
Is it already sutiable as `cargo run` accelerator?

### ISSUE THREAD

**Issue by vi** [bjorn3/rustc_codegen_cranelift#1052]
As far as I understand, one of potential uses for Cranelift is accelerating `cargo run`  during debugging.

Does `rustc_codegen_cranelift` already meet this goal for projects within its limits (i.e. not using SIMD or FFI)? If yes, what is the setup? Is there something like `cargo cranelift` as drop-in `cargo run` replacement?

Either way, status should be mentioned in README somehow (i.e. "This project can already be used to accelerate development of some Rust projects" or "This project cannot be used for accelerating development for most projects. See `test.sh` for supported ones").

**Comment by bjorn3** [comment]
For a fair amount of projects it already works fine.

---

> Is there something like cargo cranelift as drop-in cargo run replacement?

Yes, `cargo.sh` in the project dir does this. It runs cargo with the right `RUSTFLAGS` env var set and automatically uses the rustc version for which cg_clif has been compiled. For example:

```bash
$ CHANNEL="release" $cg_clif_dir/cargo.sh run
```

---

> Either way, status should be mentioned in README somehow (i.e. "This project can already be used to accelerate development of some Rust projects" or "This project cannot be used for accelerating development for most projects. See test.sh for supported ones").

Maybe below the ":warning::warning::warning: Certain kinds of FFI don't work yet. :warning::warning::warning:" there could be:

> The goal of this project is to create an alternative codegen backend for the rust compiler based on [Cranelift](https://github.com/bytecodealliance/wasmtime/blob/master/cranelift). This has the potential to improve compilation times in debug mode. If your project doesn't use any of the things listed under "Not yet supported", it should probably work fine. If not please open an issue.

**Comment by playXE** [comment]
Is it possible to somehow force this project use "emulated" cpuid through FFI e.g with C? I want to build my project with it for debug builds but it fails with cpuid :(

**Comment by vi** [comment]
@playXE , Maybe this question should be posted as a separate issue?

This one is primarily about documentation and project scope.

**Comment by vi** [comment]
Indeed, using `cargo.sh` works and even gives some speedup for full rebuilds (but not for trivial incremental rebuild where it is slower).

README should be a bit longer about usage (preparing a quick PR from Github UI).

**Comment by bjorn3** [comment]
> but not for trivial incremental rebuild where it is slower

For what project? This may be caused by https://github.com/bjorn3/rustc_codegen_cranelift/issues/762. Also how much slower is it?

**Comment by vi** [comment]
For [this one](https://github.com/vi/postsse).

```
$ touch src/main.rs  && cargo build
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
    Finished dev [unoptimized + debuginfo] target(s) in 1.99s
$ touch src/main.rs  && cargo build
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
    Finished dev [unoptimized + debuginfo] target(s) in 2.00s
$ touch src/main.rs  && cargo build
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
    Finished dev [unoptimized + debuginfo] target(s) in 1.92s
```

```
$ ( export CHANNEL=release; touch src/main.rs   && /mnt/src/git/rustc_codegen_cranelift/cargo.sh build )
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
[postsse                       : codegen mono items] start
[postsse                       : codegen mono items] end time: 1.423973891s
    Finished dev [unoptimized + debuginfo] target(s) in 2.71s
$ ( export CHANNEL=release; touch src/main.rs   && /mnt/src/git/rustc_codegen_cranelift/cargo.sh build )
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
[postsse                       : codegen mono items] start
[postsse                       : codegen mono items] end time: 1.526996414s
    Finished dev [unoptimized + debuginfo] target(s) in 2.84s
$ ( export CHANNEL=release; touch src/main.rs   && /mnt/src/git/rustc_codegen_cranelift/cargo.sh build )
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
[postsse                       : codegen mono items] start
[postsse                       : codegen mono items] end time: 1.441689737s
    Finished dev [unoptimized + debuginfo] target(s) in 2.74s
```

```
$ touch src/main.rs && RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo build
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
    Finished dev [unoptimized + debuginfo] target(s) in 0.94s
$ touch src/main.rs && RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo build
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
    Finished dev [unoptimized + debuginfo] target(s) in 0.93s
$ touch src/main.rs && RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo build
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
    Finished dev [unoptimized + debuginfo] target(s) in 0.88s
```

After modifying:

```diff
diff --git a/config.sh b/config.sh
index 9a745ad..f3043ad 100644
--- a/config.sh
+++ b/config.sh
@@ -15,7 +15,7 @@ TARGET_TRIPLE=$HOST_TRIPLE
 #TARGET_TRIPLE="x86_64-pc-windows-gnu"
 #TARGET_TRIPLE="aarch64-unknown-linux-gnu"

-linker=''
+linker='-C link-arg=-fuse-ld=lld'
 RUN_WRAPPER=''
 if [[ "$HOST_TRIPLE" != "$TARGET_TRIPLE" ]]; then
    if [[ "$TARGET_TRIPLE" == "aarch64-unknown-linux-gnu" ]]; then
```

```
  = note: ld.lld: error: can't create dynamic relocation R_X86_64_64 against symbol: std::sys::unix::args::imp::ARGV_INIT_ARRAY::init_wrapper::h2e1f40e42719be71 in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
          >>> defined in /mnt/src/git/rustc_codegen_cranelift/build_sysroot/sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd.rlib(std.4wc6fj0sdfl4hunt.rcgu.o)
          >>> referenced by 4wc6fj0sdfl4hunt.o
          >>>               std.4wc6fj0sdfl4hunt.rcgu.o:(std::sys::unix::args::imp::ARGV_INIT_ARRAY::h5712c7aebe4a0e3d) in archive /mnt/src/git/rustc_codegen_cranelift/build_sysroot/sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd.rlib
```

**Comment by bjorn3** [comment]
Thanks! Opened #1055 for the linker error.

**Comment by vi** [comment]
`end time: 1.526996414s` is still larger than total time when standard codegen is used (even including the LLD linking).

**Comment by bjorn3** [comment]
I found the reason cg_clif was slower in the incremental case. To help with development I had disabled the incremental cache in `config.sh`, which is sourced by `cargo.sh`. Removing `export CG_CLIF_INCR_CACHE_DISABLED=1` from `config.sh` made cg_clif almost twice as fast as cg_llvm.

Before:

```
hyperfine --warmup 1 "touch src/main.rs; CHANNEL="release" ../cargo.sh build" "touch src/main.rs; cargo build"
Benchmark #1: touch src/main.rs; CHANNEL=release ../cargo.sh build
  Time (mean ± σ):      2.049 s ±  0.043 s    [User: 1.667 s, System: 0.267 s]
  Range (min … max):    2.016 s …  2.145 s    10 runs
 
Benchmark #2: touch src/main.rs; cargo build
  Time (mean ± σ):      1.618 s ±  0.034 s    [User: 1.249 s, System: 0.322 s]
  Range (min … max):    1.584 s …  1.690 s    10 runs
 
Summary
  'touch src/main.rs; cargo build' ran
    1.27 ± 0.04 times faster than 'touch src/main.rs; CHANNEL=release ../cargo.sh build'
```

After:

```
hyperfine --warmup 1 "touch src/main.rs; CHANNEL="release" ../cargo.sh build" "touch src/main.rs; cargo build"
Benchmark #1: touch src/main.rs; CHANNEL=release ../cargo.sh build
  Time (mean ± σ):      1.000 s ±  0.021 s    [User: 777.9 ms, System: 251.6 ms]
  Range (min … max):    0.979 s …  1.041 s    10 runs
 
Benchmark #2: touch src/main.rs; cargo build
  Time (mean ± σ):      1.942 s ±  0.461 s    [User: 1.546 s, System: 0.362 s]
  Range (min … max):    1.553 s …  2.711 s    10 runs
 
Summary
  'touch src/main.rs; CHANNEL=release ../cargo.sh build' ran
    1.94 ± 0.46 times faster than 'touch src/main.rs; cargo build'
```

I don't really know what to do about this. During development `CG_CLIF_INCR_CACHE_DISABLED=1` is essential to prevent accidentally using outdated artifacts from incremental cache, but for end users it is bad. If I unset `CG_CLIF_INCR_CACHE_DISABLED` in `cargo.sh` I am afraid I will forget about this during development.

**Comment by vi** [comment]
> I don't really know what to do about this.

Options:

1. Two frontends: end-user frontend and developer frontent. `cargo.sh` and `cargo_dev.sh`.
2. Separate `cargo install`able project to make it easy for users to run cg_clif. Like `cargo clif_run` / `cargo clif_build` and it will download and build cg_clif under the hood. This leaves `cargo.sh` script aimed at development.
3. Default to `CG_CLIF_INCR_CACHE_DISABLED=0` for `CHANNEL=release` and to `CG_CLIF_INCR_CACHE_DISABLED=1` for `CHANNEL=debug`.

**Comment by vi** [comment]
With this patch:

```diff
diff --git a/config.sh b/config.sh
index 9a745ad..15c7732 100644
--- a/config.sh
+++ b/config.sh
@@ -44,4 +44,4 @@ export LD_LIBRARY_PATH="$(pwd)/target/out:$(pwd)/build_sysroot/sysroot/lib/rustl
 export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH
 
 export CG_CLIF_DISPLAY_CG_TIME=1
-export CG_CLIF_INCR_CACHE_DISABLED=1
+#export CG_CLIF_INCR_CACHE_DISABLED=1
```

I get the speedup:

```
$ ( export CHANNEL=release; touch src/main.rs   && /mnt/src/git/rustc_codegen_cranelift/cargo.sh build )
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
[postsse                       : codegen mono items] start
[postsse                       : codegen mono items] end time: 13.758165ms
    Finished dev [unoptimized + debuginfo] target(s) in 1.26s
$ ( export CHANNEL=release; touch src/main.rs   && /mnt/src/git/rustc_codegen_cranelift/cargo.sh build )
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
[postsse                       : codegen mono items] start
[postsse                       : codegen mono items] end time: 13.843326ms
    Finished dev [unoptimized + debuginfo] target(s) in 1.34s
$ ( export CHANNEL=release; touch src/main.rs   && /mnt/src/git/rustc_codegen_cranelift/cargo.sh build )
   Compiling postsse v0.1.0 (/home/vi/code/postsse)
[postsse                       : codegen mono items] start
[postsse                       : codegen mono items] end time: 14.483938ms
    Finished dev [unoptimized + debuginfo] target(s) in 1.30s
```

Note: setting `CG_CLIF_INCR_CACHE_DISABLED` to `0` instead of `1` is counter-intuitively equivalent to leaving it at `1`.

Waiting for `lld` support to unleash the real speedup.

**Comment by bjorn3** [comment]
> Two frontends: end-user frontend and developer frontent. cargo.sh and cargo_dev.sh.

This is probably the best option.

> Note: setting CG_CLIF_INCR_CACHE_DISABLED to 0 instead of 1 is counter-intuitively equivalent to leaving it at 1.

I think I used `env::var().is_ok()`, which only checks for the existence of the env var.

**Comment by bjorn3** [comment]
I moved the `export CG_CLIF_INCR_CACHE_DISABLED=1` from config.sh to test.sh, so cargo.sh isn't affected by it anymore.
