### ISSUE TITLE
[rustc bug with workaround] Test Suite ICE for miniz_oxide

### ISSUE THREAD

**Issue by theduke** [bjorn3/rustc_codegen_cranelift#1072]
I'm getting an ICE while running `./test.sh --release`.

Log with backtrace attached below.

Is this expected or worthy of a report?

Environment:
Commit: 4757371aba4e8aaf2cebb4ba32299cf7f9364aaf
OS/Arch: Linux desktop-1 5.4.55 #1-NixOS SMP Fri Jul 31 16:39:32 UTC 2020 x86_64 GNU/Linux
rustc: rustc 1.47.0-nightly (9b88e0a86 2020-08-15)

[log.txt](https://github.com/bjorn3/rustc_codegen_cranelift/files/5081203/log.txt)

**Comment by bjorn3** [comment]
Is this the first time you ran `./test.sh --release` or the second? If it is the second then https://github.com/rust-lang/rust/issues/74946 is likely the cause. As a workaround you can add `CARGO_INCREMENTAL=0 ` at the start of https://github.com/bjorn3/rustc_codegen_cranelift/blob/4757371aba4e8aaf2cebb4ba32299cf7f9364aaf/build_sysroot/build_sysroot.sh#L21.

**Comment by bjorn3** [comment]
ICE's in the test suite are never expected. I always run it before pushing any changes and CI runs it.

**Comment by theduke** [comment]
`CARGO_INCREMENTAL=0` does indeed fix it.

**Comment by bjorn3** [comment]
I will leave this open for when other people hit the same issue.
