### ISSUE TITLE
CG_CLIF_DISPLAY_CG_TIME clarifications

### ISSUE THREAD

**Issue by m4b** [bjorn3/rustc_codegen_cranelift#1088]
Wanted to get some clarification on `CG_CLIF_DISPLAY_CG_TIME` output; specifically the "mono items" output, i see, e.g.:

```
[iced_wgpu                     : codegen mono items] start
[iced_wgpu                     : codegen mono items] end time: 3.635323311s
```

Is the 3.6 seconds the entire time it took to compile `iced_wgpu` w.r.t. codegen backend? e.g., it doesn't include typechecking, and macro expansion, and etc., yes?

I ask because eyeballing some compilation times they appear to be much larger than the mono items output?

Lastly, are there any other start/end times besides mono items that should be reported?

**Comment by bjorn3** [comment]
> e.g., it doesn't include typechecking, and macro expansion, and etc., yes?

Correct. This only includes the actual time spent on generating object files. It doesn't include the time spent in the frontend nor the linker.

> Lastly, are there any other start/end times besides mono items that should be reported?

This is the most important for cg_clif. All other tines that may be relevant are behind `-Zself-profile`.
