### ISSUE TITLE
Is there a way I can sponsor this project?

### ISSUE THREAD

**Issue by mkpankov** [bjorn3/rustc_codegen_cranelift#1090]
Hey,
Do you have Patreon / OpenCollective / GitHub Sponsorship page?
I'd like to support the project.

**Comment by bjorn3** [comment]
Thanks a lot! I have a liberapay page: https://liberapay.com/bjorn3

**Comment by mkpankov** [comment]
Cool!
You might want to put that into README for more reach :wink:
