### ISSUE TITLE
How to use with Rust Analyzer?

### ISSUE THREAD

**Issue by Knarkzel** [bjorn3/rustc_codegen_cranelift#1112]
How can I make it so that I can build with `cranelift`, yet still be able to use Rust Analyzer (with Vim, for instance)? Currently they both delete each others cache (I believe), which results in compiling from scratch everytime I do an edit. How to bypass/fix this?

**Comment by bjorn3** [comment]
You can use the following config I think:

```jsonc
{
    "rust-analyzer.checkOnSave.overrideCommand": ["/path/to/cg_clif/build/cargo.sh", "check", "--message-format=json"]
}
```

**Comment by Knarkzel** [comment]
Oh nice, this works!
