### ISSUE TITLE
Is there any way to detect cranelift backend in #[cfg]?

### ISSUE THREAD

**Issue by playXE** [bjorn3/rustc_codegen_cranelift#1125]
I have some library that uses inline assembly and I can't build it properly with cranelift backend as there is no inline assembly support so I would like to use generic implementation when cranelift backend is used, is there any way to detect it? Example

```rust
#[cfg(cranelift)]
asm!("mov {},rsp",out(reg) sp);
#[cfg(not(cranelift)]
sp = generic_get_sp();
```

**Comment by bjorn3** [comment]
There is no way for cg_clif to mutate the session to add another cfg. If you use an explicit register instead of letting the backend choose, it should work with cg_clif on Linux though.

**Comment by playXE** [comment]
Thanks for help! Then I guess I'll just add feature flag to get proper built with cranelift backend.
