### ISSUE TITLE
`i64::MAX.checked_mul(2)` returns incorrect value

### ISSUE THREAD

**Issue by jhpratt** [bjorn3/rustc_codegen_cranelift#1162]
```rust
#[test]
fn checked_mul() {
	assert_eq!(i64::MAX.checked_mul(2), None);
}
```

This test should pass but does not. It instead returns `Some(-2)`, indicating wrapping arithmetic. This test passes for `i8`, `i16`, `i32`, and `i128`. Only `i64` (and the equivalent `isize`) fail.

I discovered this while randomly running the test suite on the time crate's main branch, where it fails in this situation only. Everything else looks great 👍🏼

**Comment by bjorn3** [comment]
Thanks for the report! `i64` has a different overflow checking method from `i8`/`i16`/`i32` and `i128`. It must be a problem there: https://github.com/bjorn3/rustc_codegen_cranelift/blob/53bfc6729ae4a53c8092473452de7a272224df5d/src/num.rs#L268-L284
