### ISSUE TITLE
#[link_section]: set correct segment for Mach-O files

### ISSUE THREAD

**Issue by eggyal** [bjorn3/rustc_codegen_cranelift#1168]
There's a FIXME comment in the source code

https://github.com/bjorn3/rustc_codegen_cranelift/blob/88901ca9d438787cf68874c9c2a65d0a95bbc010/src/constant.rs#L376-L379

but I couldn't find an issue to track it.

For information: I hit this when building the log crate with dev channel rustc.  sval-rs/value-bag#22 resulted in use of the ctor crate, which uses `#[link_section = "__DATA,__mod_init_func"]` on MacOS: because cg_clif placed the whole string in the section name, gimli/object subsequently panicked while emitting MachO.

Is it not sufficient to split the link_section on `,` for all targets?

**Comment by bjorn3** [comment]
ELF doesn't put any segments in object files. Only linked shared libraries and executables have segments. I think it is best to keep the segment name handling specific to MachO. (`tcx.sess.target.is_like_osx`)

**Comment by eggyal** [comment]
Must `#[link_section]` for MacOS targets always be in the form `segment,section`?  Not sure whether to raise an error or fallback to an empty segment name if there's no `,` — It looks like cg_llvm passes straight through to llvm purely as section name, so I guess it's llvm that then splits apart... can't find it documented either in Rust or LLVM though.

**Comment by eggyal** [comment]
Aha.  Just tried building a test project containing `#[link_section = "foo"]` using cg_llvm and got

<pre>
LLVM ERROR: Global variable '_ZN12link_section3foo17h58fcd2b94bfba06fE' has an invalid section specifier 'foo': mach-o section specifier requires a segment and section separated by a comma
</pre>
