### ISSUE TITLE
Failure with sha-1 crate due to cpuid

### ISSUE THREAD

**Issue by vi** [bjorn3/rustc_codegen_cranelift#1173]
It builds, but when running it fails:

```
trap at Instance { def: Item(WithOptConstParam { did: DefId(1:12896 ~ core[8231]::core_arch::x86::cpuid::__cpuid_count), const_param_did: None }), substs: [] } (_ZN4core9core_arch3x865cpuid13__cpuid_count17hcfa5bc63bfe66a21E): __cpuid_count arch intrinsic doesn't yet support specified
```

Workaround: use "force-soft" feature of `sha-1`:

    sha-1={version="0.9", features=["force-soft"]}

**Comment by bjorn3** [comment]
sha-1 uses cpufeatures which requests leaf 7 of the cpuid. std_detect (which provides `is_*_feature_detected!()`) only uses leaf 0, 1, 0x8000_0000 and 0x8000_0001, which means that I only implemented a fake cpuid for those leafs. cpufeatures also requires leaf 7 subleaf 0.

**Comment by bjorn3** [comment]
All subleaves of leaf 7 now return 0.
