### ISSUE TITLE
Are there plans to eventually use `mold`?

### ISSUE THREAD

**Issue by vi** [bjorn3/rustc_codegen_cranelift#1185]
[mold](https://github.com/rui314/mold) seems to aim to be even faster `lld`, so may be of interest to cg_clif.

**Comment by bjorn3** [comment]
I am aware of mold. cg_clif uses the linker code of rustc, so it always uses the same linker. I believe mold has a wrapper that ensures that mold is used as linker. Apart from that if you want mold to be used by cg_clif by default, it will likely need to become the default for rustc as a whole. The GPL license may be a problem for shipping mold with rustc though as rust prefers more permissive licenses.

**Comment by bjorn3** [comment]
This is not really actionable on cg_clif's side, so I will close this issue.

**Comment by D1plo1d** [comment]
For anyone else who reaches this issue looking for how to use mold with cg_clif the following works for me:

```bash
mold -run $cg_clif_dir/build/cargo-clif build
```
