### ISSUE TITLE
How do I prepare cg_clif for speeding up development without leaving dev/test deps around?

### ISSUE THREAD

**Issue by vi** [bjorn3/rustc_codegen_cranelift#1190]
`./y.rs prepare` +  `./y.rs build` seem to leave hundreds of megabytes-worth of `rand`, `simple_raytracer` and intermediate compilation files that are seemingly not relevant for using cg_clif's cargo script.

Maybe there should also be `./y.rs deploy` and `./y.rs clean`?

**Comment by bjorn3** [comment]
After a build you can copy the `build` dir and then use `./clean_all.sh` to remove all compilation artifacts.
