### ISSUE TITLE
ICE on iced-x86 compilation

### ISSUE THREAD

**Issue by DCNick3** [bjorn3/rustc_codegen_cranelift#1226]
Tried to build a project using [iced-x86](https://github.com/icedland/iced/tree/master/src/rust/iced-x86) and it fails with an ICE

The output is quite large, so I uploaded it as a gh gist: https://gist.github.com/DCNick3/f438d0676e92ed8794ccb79b8375c1cf

rustc_codegen_cranelift is ddde38d1323f103c55710a8b9599feb0f76ea186 (current master).

**Comment by bjorn3** [comment]
Thanks for the report! This seems to be a bug in the check if two types are compatible. The two mentioned types differ only in a lifetime. As workaround you can comment out https://github.com/bjorn3/rustc_codegen_cranelift/blob/ddde38d1323f103c55710a8b9599feb0f76ea186/src/value_and_place.rs#L423

**Comment by DCNick3** [comment]
iced-x86 does compile with this workaround applied, thanks!

**Comment by bjorn3** [comment]
Fix it. I missed a case in `assert_assignable`. iced-x86 compiles fine for me now.
