### ISSUE TITLE
Is there a way to get the clif the frontend outputs?

### ISSUE THREAD

**Issue by transparent123123** [bjorn3/rustc_codegen_cranelift#1232]
I'm now trying to get what cranelift is doing in each pass. And want to see what is the performance for each benchmark test for the backend. If there is a easy way for me to get the ir(clif) translated from rust? @bjorn3

**Comment by bjorn3** [comment]
You can pass `--emit llvm-ir` to rustc. For example using `RUSTFLAGS="--emit llvm-ir". When using cg_clif it will create a directory with the `.clif` extension containing the ir for every function compiled right after translation, after clif ir level optimizations and the vcode produced by the cranelift target backend. I admit that it is confusingly named, as no llvm ir is created. Unfortunately rustc doesn't allow creating custom `--emit` kinds. This `--emit` kind was created back when LLVM was the only codegen backend supported by rustc.

**Comment by eggyal** [comment]
Perhaps there should be a `backend-ir` emit type or something, and `llvm-ir` alias (and eventually be deprecated in favour of) it.

**Comment by transparent123123** [comment]
thanks a lot!
