### ISSUE TITLE
benchmark test with huge gap compared with llvm backend

### ISSUE THREAD

**Issue by transparent123123** [bjorn3/rustc_codegen_cranelift#1245]
I tried some benchmark test on both default llvm backend and cranelift backend. [https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust.html](url)

The test was taken by the following steps.(i ran it in the same machine)
```
cargo build --release
time ./binary

cranelift cargo build --release
time ./binary 
```
there are huge gaps of execution time. I tried n-body, mandelbort, binary-trees. And the result is as follow 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\T00595~1\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\T00595~1\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

  | llvm | cranelift
-- | -- | --
n-body |   |  
real | 0m9.298s | 1m57.644s
user | 0m9.290s | 1m57.638s
sys | 0m0.009s | 0m0.005s
  |   |  
mandelbrot | 0m3.830s | 3m20.857s
  | 0m13.769s | 37m5.847s
  | 0m0.372s | 0m0.448s
  |   |  
binary-trees | 0m1.809s | 0m16.354s
  | 0m9.595s | 2m0.253s
  | 0m0.188s | 0m0.173s

</body>

</html>

is it normal to have such a gap ? or is there some extra arg to add when compiling to make it faster?
@bjorn3

**Comment by bjorn3** [comment]
You should compare debug mode in both cases. Cranelift only supports a couple of minor optimizations. Even inlining is not supported as every function is compiled independently. Rustc_codegen_cranelift is solely meant for unoptimized builds during development. Once you want to release your program you will have to use LLVM to make it run fast.
