### ISSUE TITLE
Enabling s390x on CI

### ISSUE THREAD

**Issue by afonso360** [bjorn3/rustc_codegen_cranelift#1259]
👋 Hey,

It looks like cg_clif works on s390x! 🎉  Thanks @uweigand!

Should we add a qemu runner on CI to prevent regressions? (We probably need to wait for cranelift 0.88 to be released)

I'm up for doing this, if so.

**Comment by bjorn3** [comment]
:100: We should definitively test it on CI!

**Comment by uweigand** [comment]
Agreed!  We already have a qemu runner for wasmtime, so this should in principle work.   We do need at least QEMU 6.1 to make sure all instructions generated by cranelift are properly supported.
