### ISSUE TITLE
The `./y.rs prepare` script doesn't recognize distro package manager installations of Rust.

### ISSUE THREAD

**Issue by Supermath101** [bjorn3/rustc_codegen_cranelift#1308]
I installed Rust via the instructions on [Fedora's website](https://developer.fedoraproject.org/tech/languages/rust/rust-installation.html), and tried to start the build process by running `./y.rs prepare`. Then, a Rust program panicked with the following error message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', ./build_system/rustc_info.rs:41:10
```
After looking at the source file where the panic occurred, I saw [some code](https://github.com/rust-lang/rust/blob/ba64ba8b0dfd57f7d6d7399d0df7ded37d2af18d/compiler/rustc_codegen_cranelift/build_system/rustc_info.rs#L27) calling the `rustup` binary.

So, is there a way to rewrite this to not depend on `rustup`?

**Comment by bjorn3** [comment]
Cg_clif depends on a specific nightly version of rustc as indicated by rust-toolchain.toml. In addition it needs the rustc-dev rust component to be able to link against rustc itself. Your distro is highly unlikely to have the correct rustc nightly. As such you will have to use rustup for now. I'm working on getting cg_clif distributed as rust component too. But even then it will likely only be available on nightly rustc for quite some time.
