### ISSUE TITLE
[question] use cranelift with rust-analyzer

### ISSUE THREAD

**Issue by alexzanderr** [bjorn3/rustc_codegen_cranelift#1335]
hello

i want to know if i can use cranelift with rust-analyzer, because rust-analyzer messes up my target directory.

how? when i open the editor, rust-analyzer starts building again from scratch. when i close the editor and build in the command line with `cargo-clif`, the build is done again from the beginning.

so there are different build artfiacts, ofcourse, and that is a problem.

**Comment by bjorn3** [comment]
Resolved in https://github.com/rust-lang/rust-analyzer/issues/13878
