### ISSUE TITLE
Support stack probing

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#661]
This is used to prevent Stack Clash, where the stack grows down to the heap, corrupting values on the heap.

**Comment by bjorn3** [comment]
@sunfishcode is `__cranelift_probestack` compatible with [`__rust_probestack`](https://github.com/rust-lang-nursery/compiler-builtins/blob/master/src/probestack.rs)?

**Comment by sunfishcode** [comment]
Yes. The precise probestack convention can be controlled by the `probestack_func_adjusts_sp` and `probestack_size_log2` settings, but the default settings are compatible with `__rust_probestack`.

One way to tell cranelift to use the name `__rust_probestack` is to pass a custom libcall_names mapping function to `FaerieBuilder`/`SimpleJITBuilder`::new.

**Comment by bjorn3** [comment]
> is to pass a custom libcall_names mapping function to FaerieBuilder/SimpleJITBuilder::new.

That is exactly what I wanted to do. I just didn't want to get surprised by a hard to debug error originating from an abi incompatibility :)

**Comment by bjorn3** [comment]
I do need to find a way to avoid the inline asm version used by compiler builtins first.

**Comment by bjorn3** [comment]
Inline stack probing is enabled on x86_64 now. Cranelift 0.91 will support it on AArch64 too.
