### ISSUE TITLE
Support -Ctarget-cpu

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#690]

**Comment by bjorn3** [comment]
This can be implemented by setting the right target cpu at https://github.com/bjorn3/rustc_codegen_cranelift/blob/29a4a551eb23969cde9a895d081bee682254974c/src/lib.rs#L279.

**Comment by mominul** [comment]
I'd like to take this!

**Comment by bjorn3** [comment]
Go for it!
