### ISSUE TITLE
Patch libstd arg initialization for rust#66547

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#804]
Once https://github.com/rust-lang/rust/pull/66547 lands, the linux-gnu target will use `#[link_section]` to initialize the list of arguments. Because `cranelift-module` doesn't provide an api to place functions and statics in a specific section, we will need to patch libstd to revert the rust PR.

**Comment by joshtriplett** [comment]
This seems unfortunate. Is there any plan to support writing things to different sections in the cranelift backend?

**Comment by bjorn3** [comment]
`object` does support this, so by modifying `cranelift-object` it should be possible to implement it. `faerie` however only has support for custom sections to which nobody refers to. For `cranelift-simplejit` it wouldn't even make sense to support this, as no object files are emitted. The SimpleJIT backend currently supports passing arguments to the jitted code, however when linking to libstd, we load the dylib for it. By using `.init_array`, the loaded libstd will get initialized with the arguments of the rustc process itself, instead of the content of the `JIT_ARGS` env var, which cg_clif passes to the generated `main` shim.

I think it would be the best if the args passed to `main` would be used whenever possible. It could for example override the args set by `.init_array`.

**Comment by bjorn3** [comment]
Patched in https://github.com/bjorn3/rustc_codegen_cranelift/commit/b97df0b07fb925f7b0894b661afaad2413a3242e.
