### ISSUE TITLE
unexpectedly slow compile benchmark

### ISSUE THREAD

**Issue by eminence** [bjorn3/rustc_codegen_cranelift#865]
Hello!

I'm trying out rustc_codegen_cranelift for the first time.   I'm having two problems, that may or may not be related.

The first is an unexpectedly slow compile times in a benchmark that I saw from the output of running `./test.sh`:

```
[BENCH COMPILE] ebobby/simple-raytracer                        
Benchmark #1: RUSTFLAGS='' cargo build --target x86_64-unknown-linux-gnu                                                                                                 
  Time (mean ± σ):     37.339 s ±  1.593 s    [User: 52.483 s, System: 4.260 s]                      
  Range (min … max):   35.432 s … 39.913 s    10 runs                         
                                                                                               
Benchmark #2: ../cargo.sh build                                                 
  Time (mean ± σ):     877.413 s ± 18.198 s    [User: 157.266 s, System: 19.223 s]
  Range (min … max):   848.567 s … 902.356 s    10 runs                                              
                                                                                                                             
Summary                                                                                                        
  'RUSTFLAGS='' cargo build --target x86_64-unknown-linux-gnu' ran                                   
   23.50 ± 1.11 times faster than '../cargo.sh build'                               
```

The second problem (which I can't tell is related) is that test.sh never finishes, as it gets hung up compiling regex:

```
   Compiling regex v1.2.0 (/nas/achin/devel/rustc_codegen_cranelift/regex)
[codegen mono items] start
[codegen mono items] start
warning: err opening clif file: Os { code: 36, kind: Other, message: "File name too long" }                                                                              

[codegen mono items] start
[codegen mono items] start
[codegen mono items] start
[codegen mono items] start
[codegen mono items] start
[codegen mono items] start
Building [===========================================>             ] 34/44: regex, nfa(test), default-bytes(test), default(test), backtrack-bytes(test), backtrac... 
```
(If i'm reading this output correctly, this is from the `[TEST] rust-lang/regex example shootout-regex-dna` section)

## Versions:

rustc_codegen_cranelift version: 4fbb45c3f3673091075a0a7fc91bbf8abe777f36
rustc version: rustc 1.42.0-nightly (3ebcfa145 2020-01-12)

**Comment by bjorn3** [comment]
Did you run it in debug mode (`./test.sh`) instead of release mode (`./test.sh --release`) on WSL1? In debug mode cg_clif writes the clif ir for every function to `target/out/clif`. The Windows kernel (as used by WSL1) doesn't like huge amounts of files being written. I will update the readme to run cg_clif in release mode.

**Comment by eminence** [comment]
Thanks for the hint about using `--release`, that helped, a lot!

```
[BENCH COMPILE] ebobby/simple-raytracer
Benchmark #1: RUSTFLAGS='' cargo build --target x86_64-unknown-linux-gnu
  Time (mean ± σ):     37.870 s ±  5.127 s    [User: 52.287 s, System: 4.212 s]
  Range (min … max):   34.288 s … 51.975 s    10 runs

Benchmark #2: ../cargo.sh build
  Time (mean ± σ):     26.956 s ±  3.034 s    [User: 31.423 s, System: 4.260 s]
  Range (min … max):   23.724 s … 34.284 s    10 runs

Summary
  '../cargo.sh build' ran
    1.40 ± 0.25 times faster than 'RUSTFLAGS='' cargo build --target x86_64-unknown-linux-gnu'
```

This also solved my other problem, as `./test.sh --release` now runs to completion in under an hour.

Sorry that I did not include any details of my system in my original issue.  I am on Linux, running out of a NFS-mounted directory.

**Comment by bjorn3** [comment]
```
   '../cargo.sh build' ran
     1.40 ± 0.25 times faster than 'RUSTFLAGS='' cargo build --target x86_64-unknown-linux-gnu'
```

That is a much bigger difference than for me!

>  I am on Linux, running out of a NFS-mounted directory.

NFS likely can't handle much files either :)

**Comment by eminence** [comment]
I also tried running out of a local SSD array, but the results were faster, but less interesting :)

```
[BENCH COMPILE] ebobby/simple-raytracer
Benchmark #1: RUSTFLAGS='' cargo build --target x86_64-unknown-linux-gnu
  Time (mean ± σ):     19.047 s ±  0.209 s    [User: 51.417 s, System: 3.704 s]
  Range (min … max):   18.836 s … 19.523 s    10 runs

Benchmark #2: ../cargo.sh build
  Time (mean ± σ):     18.125 s ±  0.165 s    [User: 31.203 s, System: 4.485 s]
  Range (min … max):   17.822 s … 18.392 s    10 runs

Summary
  '../cargo.sh build' ran
    1.05 ± 0.01 times faster than 'RUSTFLAGS='' cargo build --target x86_64-unknown-linux-gnu'
```

**Comment by bjorn3** [comment]
Interesting. I am now curious why cg_llvm is much slower with NFS than on an SSD. Maybe because cg_llvm uses multiple codegen units, which are each written separately to the disk, whil cg_clif uses only one codegen unit for each crate?

**Comment by eminence** [comment]
Hmm, yeah I guess I didn't expect a local SSD to be that much faster than my NFS mount.  Running a normal "cargo build" on a small project (not using your cranelift backend) on SSD is about twice as fast:

```
Summary
  './build_ssd.sh' ran
    2.15 ± 0.08 times faster than './build_nfs.sh'
```
